philss/floki

mix.exs

Since `mochiweb` is a runtime dependency, it needs to be included in the application config when using exrm releases. Here's the error I was getting on my server if I didn't put `:mochiweb` in my own app's config.
```
** (exit) an exception was raised:
** (ErlangError) erlang error: :"module could not be loaded"
:mochiweb_html.parse("<floki><!DOCTYPE html PUBLI….
```

Update mix.exs to include :mochiweb in application configuration

---

.travis.yml
mix.exs

This PR excludes the `src/*.erl` files from package generation by only reading the `src/*.xrl` files.
This is needed because we shouldn't include the compiled lexer in the new packages.
Fixes #24

Fix compilation on Erlang 17.5

---

lib/floki.ex
lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector_parser.ex
test/floki_test.exs

With this feature, Floki is able to search sibling nodes, using the plus
combinator. Eg.: Floki.find(html, "h2 + a") => return anchors that are
siblings of "h2" nodes.
Specs: http://www.w3.org/TR/css3-selectors/#adjacent-sibling-combinators
Closes #16

Add adjacent sibling selector

---

lib/floki/finder.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki_test.exs

This feature enables searching for general siblings, like described in
the spec:
http://www.w3.org/TR/css3-selectors/#general-sibling-combinators
Closes #28

Add general sibling combinator

---

lib/floki.ex
test/floki_test.exs

Node tree with comments was crashing before this fix.

Fix HTML comment in raw_html

---

lib/floki.ex
lib/floki/filter_out.ex

First I added a function that filter out specific tags
Then I used this function to filter out script tags by default in the `text` function. I think that you generally do not want to get the js content of `<script>` when you use the function text.

Add function to filter out tags and remove js from text function

---

lib/floki/deep_text.ex
test/floki/deep_text_test.exs

Not sure if this is in line with the design philosophy for Floki, but I thought for a DeepText text extraction, \<br> nodes should be changed into \n. The reason being that it retains the layout intent of the text itself and a \<br> node is a terminal node in that it can't have children or text (compared to a \<p>).
Furthermore, the \n can easily be replaced in the resulting plain text if you want the old result, whereas you can't insert a newline at this point. 
Please feel free to reject the pull request if you don't agree with the change and I can maintain a fork of the library for my own purposes.

For DeepText <br> nodes are replaced by newline (\n)

---

lib/floki.ex
test/floki_test.exs

The function `Floki.raw_html/1` does not handle boolean attributes.
A boolean attribute is one who's lack of corresponding value indicates truthiness. For example:
```html
<div hidden></div>
```
Since attributes in Floki's AST are represented as a 2 element tuple, there is no clear way to render an AST with boolean values.
Update the rendering code to support rendering attributes that are not a 2 element tuple.
```elixir
Floki.raw_html({"div", ["hidden"], []})
"<div hidden></div>"
```
Thankfully this does not change any of the existing behavior in Floki, it just extends what is there to support another form of attribute when rendering an AST.
The above described AST, `{"div", ["hidden"], []}`, is not a valid AST produced by mochiweb_html (which is the parser used internally by Floki). In …

Support rendering boolean attributes

---

lib/floki.ex

Adding example to depict explicit usage of tree in Floki.find/2

Update docs with examples for html_tree type

---

lib/floki/finder.ex
test/floki/deep_text_test.exs
test/floki/flat_text_test.exs

Noticed the mention of `array` in the docs. I think it makes sense to reword this everywhere.

Re-word: array -> list

---

lib/floki/selector.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki/selector_parser_test.exs
test/floki/selector_tokenizer_test.exs
test/floki_test.exs

It fixes a wrong selector when searcing elements using namespace, like
is described in https://www.w3.org/TR/css3-selectors/#univnmsp.
Now you can search for elements inside namespace with:
Floki.find(html, "ns | tag")
This closes the issue #46 again.

Fix search of elements with namespace

---

lib/floki/finder.ex
test/floki_test.exs

The test was extracted from #57. That PR still has a test that fails, but that's a different issue. This PR at least addresses the original problem with immediate children.

Ensure immediate children selector is working

---

lib/floki/finder.ex
test/floki_test.exs

It fixes the search for sibling after a chain of immediate children.
The problem was in the siblings that were been passed to the traverse
child function. We had to fetch the siblings again after matching a
node.
Related to PR #57

Fix sibling after immediate children

---

config/config.exs
lib/floki/selector_parser.ex
test/floki/selector_parser_test.exs

Using the Logger's own formatter to print module-specific metadata can make further Logger additions easier.

Configure Logger format in config.exs

---

.travis.yml
CHANGELOG.md
lib/floki.ex
lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector_parser.ex
mix.exs
test/floki/selector_parser_test.exs

Since the next versions will rely on `Map` with possible millions of keys, we should run only in versions equal or above 1.2.
This PR also improves the usage of aliases with the new syntax sugar provided in Elixir 1.2.

Remove support for Elixir 1.1 and below

---

lib/floki/finder.ex
lib/floki/html_tree.ex
lib/floki/html_tree/html_node.ex
lib/floki/html_tree/id_seeder.ex
lib/floki/html_tree/text.ex
lib/floki/selector.ex
test/floki/deep_text_test.exs
test/floki/html_tree_test.exs
test/floki/selector_parser_test.exs
test/floki/selector_tokenizer_test.exs

This is needed in order to be the base of the next features such as: update tree, find nodes using the "pseudo class" :nth-child, filter out elements with selectors, and more.
With this refactor it is now easier to analyse the position and to get nodes that are related to a given node.
It closes issue #71.

Refactor Floki.Finder to use HTML Tree for traverse and search

---

README.md
lib/floki/finder.ex
lib/floki/pseudo_class.ex
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki/selector_parser_test.exs
test/floki/selector_tokenizer_test.exs
test/floki_test.exs

This version does search for specific node positions (`integers`) and `even/odd` positions. It does not work with complex expressions like "2n+1" yet.
Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child
It closes #64 .

Add support for nth-child pseudo-class selector

---

lib/floki.ex
lib/floki/filter_out.ex
lib/floki/finder.ex
lib/floki/html_tree.ex
lib/floki/html_tree/comment.ex
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki/filter_out_test.exs
test/floki/html_tree_test.exs
test/floki_test.exs

It makes filter out work with complex selectors and not only tag name. It closes #61 .
This also fixes some issues:
- Sibling selector not working as expected when there is a text node in the middle - closes #79;
- `nth-child` not ignoring text or comment nodes;
- `HTMLTree.to_tuple/2` not building comments back.

Add complex selectors for filter out

---

.travis.yml
lib/floki/finder.ex
test/floki_test.exs

Attempt at fixing #84 
Rather than finding all node_ids in a given range (using the next sibling as an upper-bound), find all the children by recursively walking down the tree looking for leaf nodes.
I've also added the test case from #84, although I'm not sure that putting that test in `test/floki_test.exs` is the best place for it.
/cc @philss

get descendant node ids recursively rather than using a range

---

lib/floki/finder.ex
test/floki_test.exs

Thanks for all of your help with #85 
I tried upgrading to `v0.12.1` in my project and ran into two small issues. This PR attempts to fix one of those two.  `Finder` was returning some duplicate nodes and the nodes were not in the same order that they occured in the html tree.
I've added a spec to highlight this and tried to address it in `Finder`.

Duplicate reversed descendant matches

---

lib/floki.ex
lib/floki/html_tree.ex
test/floki/filter_out_test.exs
test/floki/html_tree_test.exs

I first noticed this problem manifest when I would do:
```
iex> Floki.text([{"p", [], ["1"]},{"p", [], ["2"]}])
"21"
```
The order of the text was reverse of the order of the nodes being passed in. Digging in further it turned that that the reversing was happening during the `FilterOut` step, and digging in past that it turned out be caused when `Finder` constructs an `HTMLTree` struct because it was recording the `root_node_ids` in reverse order of what got passed in.
I've added a few unit tests as I was tracking this down, but we can remove most of them if you prefer. It might only be useful to keep the unit test added to `HTMLTree` since that was the root cause in the end, but I figured you might want to keep the coverage around from the other tests just in case.

Text reversing

---

CHANGELOG.md
lib/floki/finder.ex
test/floki_test.exs

The problem was related with the order that we were returning the
elements of a search using the descendant combinator.
The solution is to reverse also the nodes in the recursive call that
will reach all the children nodes.
Issue related: https://github.com/philss/floki/issues/98

Fix order of elements returned after a desdencent combinator search

---

lib/floki/finder.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

This also tweaks node_position logic so that it can be called on non-HTMLNode elements.
Fixes #102.

finder: add support for selectors that only include a pseudo-class

---

lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki/selector_parser_test.exs
test/floki_test.exs

This PR fixes: https://github.com/philss/floki/issues/100

Fix ":not()" pseudo class selector to accept pseudo-class selectors as args

---

lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki/selector_tokenizer_test.exs
test/floki_test.exs

This adds support for the `:contains` pseudo-class selector from jQuery.
Usage is demonstrated in the `contains pseudo-class` test.

add support for contains selector

---

lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector_parser.ex
src/floki_selector_lexer.xrl
test/floki/selector_parser_test.exs
test/floki_test.exs

While trying to utilize the new pseudo `not` selector, I was trying to do a selection with multiple _or_ selectors in the `not` pseudo class. i.e. `a.link:not(.bar, [style=baz])`
However, `finder.ex` was splitting the string at `,` which broke up all subsequent token parsing. So I went ahead and mocked this up to support this use-case.
Happy to change what is needed to meet any style preference or design that's not currently met. Let me know what you think.
@philss @mmmries

update pseudo not selector to allow multiple selections in ()

---

lib/floki/selector.ex
test/floki_test.exs

I found that issue during parsing `http://ruby-doc.org/stdlib-2.4.1/libdoc/psych/rdoc/Psych/Parser.html`.
It has this span on it

Fix failing finding on unescaped angles in text

---

lib/floki/html_tree.ex
mix.lock
test/floki_test.exs

I was trying to parse a page that for some unknown reason has a xml declaration tag lost inside the body tag that caused Floki to crash.
I added a test for that edge case and a quick fix that just ignores it.

fixed crash caused by xml declaration inside body

---

lib/floki/selector_parser.ex
mix.lock
test/floki/selector_parser_test.exs
test/floki_test.exs

Simple update to allow pseudo `:not()` selects to handle attribute selectors within the parenthesis:
`a.link:not([class*=baz])` etc etc
@philss 
(ps. I'm not sure if you want mix.lock, but it looks like some deps were updated it so I included. Can drop easily if needed)

Handle attribute selectors in :not()

---

lib/floki/selector_parser.ex
test/floki/selector_parser_test.exs

Since [the change to parse all tokens, a selector is returned when encountering a `:comma` token](https://github.com/philss/floki/pull/106/files#diff-7f26dd84090995cad0112f38a801b18bR32). 
When we `consume_combinators`, that calls `do_parse` which gets a selector and continues on parsing tokens. However, the selector is returned as a result of matching `:comma` token and removes it from the remaining tokens. So when parsing continues after `consume_combinator`, it continues parsing the previous selector instead of starting a new one.
This changes so `consume_combinator` functions return a selector tuple since they will get a fully completed selector after parsing.
```elixir
iex> "a b.foo c, ul a[class=bar]" |> Floki.SelectorTokenizer.tokenize |> Floki.SelectorParser.parse |> length
1
iex> …
```

Return selector after consuming combinator

---

lib/floki.ex
test/floki_test.exs

Previously it was failing with:
(Protocol.UndefinedError) protocol Enumerable not implemented for "xml"

Fix converting html_tree to raw html when it has xml prefix

---

lib/floki/attribute_selector.ex
lib/floki/combinator.ex
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki/selector_test.exs

This is needed in order to make easier to understand what a
`Floki.Selector` represents as CSS selector.

Add implementation of String.Chars protocol to Selector

---

lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector/attribute_selector.ex
lib/floki/selector/combinator.ex
lib/floki/selector/parser.ex
lib/floki/selector/tokenizer.ex
test/floki/selector/parser_test.exs
test/floki/selector/tokenizer_test.exs
test/floki/selector_test.exs

Moves some modules to the `lib/floki/selector` path in order to better
organize the code.

Organize modules related to `Selector`

---

lib/floki/html_tree.ex
test/floki/html_tree_test.exs

This enables usage of `Enum` and `Stream` functions with HTMLTree.
Related discussion: https://github.com/philss/floki/issues/118

Implement Enumerable protocol for Floki.HTMLTree

---

lib/floki.ex
lib/floki/finder.ex
test/floki_test.exs

It renames these transformation function to only `map/2` following
@aphillipo's suggestion from https://github.com/philss/floki/issues/118

Renames Floki.transform/2 and Floki.Finder#apply_transformation/2

---

.travis.yml
mix.exs

Following the policy of supporting the last three releases, we are
dropping support for Elixir 1.2.
This will enable Floki to use some features that are only available
since version 1.3.

Remove support for Elixir 1.2

---

lib/floki.ex
test/floki_test.exs

Previously the output of `raw_html` loses any text contained within self
closing tags. For example, parsing and using `raw_html` with the following:
```xml
<item>
<link>www.example.com</link>
</item>
```
resulted in:
```xml
<item>
<link/></link>
</item>
```

Fix `raw_html` for self closing tags with content

---

lib/floki/filter_out.ex
test/floki/filter_out_test.exs

It does not break. Returns an empty list instead.
The reason to not return `nil` is to keep the interface only returning
tuples and lists.
It fixes #136

Fix filter out when result is empty

---

lib/floki/html_tree.ex
test/floki/html_tree_test.exs

We need to ignore the XML tag in order to consider the XML as a kind of
HTML tree.
If fixes #138.

Ignore XML tag when building HTML tree

---

lib/floki.ex

The example wasn't displayed as code.

Fix example indentation for attr/4

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

Hello,
This PR closes #143 by adding support for the pseudo-class selector `:last-child`. A matching branch is added to `pseudo_class_match?/3` in `Floki.Selector`. Also, the `node_position/2` in `Floki.Selector.PseudoClass` is now split to `node_position/2` and `get_children_nodes_ids/2`.

Add :last-child pseudo-class selector

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

Hello,
This PR closes #144 by adding support for the pseudo-class selectors: `:nth-of-child(n)`, `:first-of-type` and `:last-of-type`.

Add :nth-of-type(n), :first-of-type, and :last-of-type pseudo-class selectors

---

lib/floki/selector/functional.ex
test/floki/selector/functional_test.exs

Now it should be according to spec: https://drafts.csswg.org/selectors-3/#nth-child-pseudo
Thanks, @mischov!

FIX Functional notation whitespace and negative b

---

lib/floki/selector/pseudo_class.ex
test/floki/selector/functional_test.exs
test/floki_test.exs

Following the implementation from https://github.com/philss/floki/pull/150

Add functional notation to nth-of-type pseudo-class selector

---

lib/floki.ex
test/floki_test.exs

Given the fact that `Floki.parse` might return plain text, it makes sense
that `Floki.raw_html` would handle that situation. Currently, plain text
will not match and function signatures for `raw_html` causing an error like
this:
```
"some text"
|> Floki.parse
|> Floki.raw_html
** (FunctionClauseError) no function clause matching in Floki.raw_html/2
The following arguments were given to Floki.raw_html/2:
"some text"
""
Attempted function clauses (showing 6 out of 6):
defp raw_html([], html)
defp raw_html(tuple, html) when is_tuple(tuple)
defp raw_html([string | tail], html) when is_binary(string)
defp raw_html([{:comment, comment} | tail], html)
defp raw_html([{:pi, "xml", attrs} | tail], html)
defp raw_html([{type, attrs, children} | tail], html)
```
This add a simple signature to just …

support raw text into `Floki.raw_html`

---

lib/floki.ex

Not sure how to add tests but the cases I tried were
`<!DOCTYPE html>`
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">`
`<!DOCTYPE note SYSTEM "Note.dtd">`
using `Floki.parse()` and `Floki.raw_html()`

Handle doctype in raw_html, fixes #155

---

lib/floki.ex
mix.exs
mix.lock
test/floki_test.exs

We need to represent the HTML entities as they originally are,
since the reparsing of the output should generate the same document.
It fixes https://github.com/philss/floki/issues/158

Re-encode HTML entities on Floki.raw_html/1

---

lib/floki.ex

`Floki.parse/1` returns binary when the string is not html, so the specs should cover it. Alternatively, you could change the `html_tree` type.

Updated specs for Floki.parse/1

---

lib/floki.ex
lib/floki/raw_html.ex
test/floki_test.exs

It does not try to encode HTML entities inside
script or style tags.
It is related with: https://github.com/philss/floki/issues/161

Fix `Floki.raw_html/1` for `script` and `style` tags

---

.ebert.yml
lib/floki.ex
lib/floki/raw_html.ex
test/floki_test.exs

Added an ebert config, as it seems that credo wasn't running prior. I also ran the formatter once more.
May I suggest that we move this project to something along the lines of https://travis-ci.org/ ? Ebert seems pretty limited

Configure ebert for credo, run format

---

lib/floki/html_tree.ex

When compiling floki, there is a compile warning that gets spit out:
```
==> floki
Compiling 1 file (.xrl)
Compiling 1 file (.erl)
Compiling 21 files (.ex)
warning: function slice/1 required by protocol Enumerable is not implemented (in module Enumerable.Floki.HTMLTree)
lib/floki/html_tree.ex:202
Generated floki app
```
The docs for `Enumerable` specify that `{:error, __MODULE__}` causes a default algorithm built on top of reduce/3 that runs in linear time will be used.

Remove Enumerable.slice compile warning

---

lib/floki/raw_html.ex
test/floki_test.exs

In case of an html comment inside `style` or `script` tags, `Floki.raw_html` raise an error `(Protocol.UndefinedError) protocol String.Chars not implemented for {:comment, "...."}`.
So instead of reimplementing the serialization, I removed the default encoder to not encode html entities.

Fix style and script tags with comments

---

lib/floki/raw_html.ex
test/floki_test.exs

fixes https://github.com/philss/floki/issues/188
Adds a type check to `Floki.RawHTML.build_attrs/2`, to ensure that the attributes are a string before checking for double quotes inside of attributes.

Check type of attribute values

---

lib/floki/selector.ex
lib/floki/selector/parser.ex
lib/floki/selector/pseudo_class.ex

Fix for Issue #192 
Sets the level of logging to info in case tokens get ignored

Change the level of logging from warn to info

---

lib/floki.ex

Add opts `style` for skip text in <style> block.  (By default is true, for backward compatibility.)

Add style block skiped in text

---

README.md

Update html5ever version in the readme to the newest one. It is compatible with Erlang/OTP 21 unlike the previous version.

Update html5ever version in README

---

lib/floki.ex
lib/floki/filter_out.ex

ElixirLS was complaining about `Floki.filter_out(_, :comment)`

Fix typespec for filter_out

---

lib/floki/html_parser/mochiweb.ex
mix.exs
src/floki_mochi_html.erl

This commit brings the mochiweb_html module and remove
the dependencies on other modules by proper equivalents
in Erlang or Elixir. Every change on the original file
has been annotated with comments, other than that the
functionality remains the same.

Bring over mochiweb_html and remove dependencies

---

lib/floki.ex
test/floki_test.exs

This new function returns the direct child nodes of a HTML tree, optionally
excluding text nodes, specially useful for pipes:
```elixir
my_html
|> Floki.find(".my-selector")
|> Floki.children(include_text: false)
|> Enum.map(&my_transform_func/1)
```
Inspired by #215

Introduces Floki.children/2 function

---

README.md

There was a change in the name of the service
https://sourcelevel.io/ebert-is-now-sourcelevel

Change Ebert README badge name to SourceLevel

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature.md

The objective is to improve the flow for people opening new issues.
It was based on AppSignal's Elixir package:
https://github.com/appsignal/appsignal-elixir

Add issue templates to make easier to open issues

---

src/floki_mochi_html.erl
test/floki_test.exs

It throws an error to the parser so it can ignore the decode of charref
when it can't get back a valid UTF8 codepoint.
This fixes #233, #235 and #237.

Fix parsing when cannot decode a charref correctly

---

.github/workflows/ci.yml
README.md
lib/floki/html_parser/fast_html.ex
mix.exs
mix.lock
test/test_helper.exs

Closes #234, closes #156 
Note that:
1. Currently html5ever and fast_html are failing exactly the same tests, I am guessing that's because of #236 and I think this should be solved in a separate PR.
2. The test code is pretty hacky, would be nice if `System.cmd` could be avoided, but I can't figure out why is `ExUnit` not running the tests without it.

Add fast_html parser and test all parsers on CI

---

README.md

Since `Floki.HTMLParser.FastHTML` doesn't exist

Fix typo of FastHtml in the readme

---

lib/floki.ex
lib/floki/parse_error.ex

Both functions have the same functionality as their respective
counterparts, but raise a `Floki.ParseError` in case of a parsing error
instead of returning an error tuple or return the successfully parsed
html tree.
This is especially useful when using the pipe operator.

Add parse_document!/1 and parse_fragment!/1

---

README.md

The possessive "its", like "his" and "hers", requires no apostrophe.

Fix improper "it's" usage.

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
mix.lock
test/floki_test.exs

It adds these two selectors following the examples from [MDN Web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/Reference).
Closes #257

Add E:nth-last-child(n) and E:nth-last-of-type(n) pseudo-class selectors

---

lib/floki.ex

Usage of `when` in function typespecs: https://hexdocs.pm/elixir/typespecs.html#defining-a-specification
P.S. Please excuse my rudeness. There was a bit of sarcasm in [that comment](https://github.com/philss/floki/pull/248#issuecomment-589118939). 🙏

Refactor spec of Floki.traverse_and_update/3

---

.github/workflows/ci.yml

It replaces the "official" imagens with images provided by the Hex team,
which are updated automatically for each branch and tag created on the
Elixir project. They are probably more stable and are released faster
than the official channel.
For more details see https://elixirforum.com/t/yet-another-elixir-and-erlang-docker-image/28740
And also check https://github.com/hexpm/bob

Use hexpm Docker images for our CI workflows

---

lib/floki/raw_html.ex
test/floki_test.exs

`Floki.raw_html` appears to encode HTML entities on attributes using
`html_escape_attribute_value/1`, but the regular expression left out
`<`, `>`, and `'` despite having clauses that match those characters in
`html_escape_char/1`. This adds those three characters to the regular
expression match, and adds unit tests to that effect.
It's also possible this was intentional and I'm missing something, so if
so I'm happy to hear why and I can close this PR.

Support Encoding More Entities in Floki.raw_html

---

.github/workflows/ci.yml

The current configuration skip configuration on all steps.

if: expression on ci file configuration doesn't work as expected

---

lib/floki.ex
lib/floki/raw_html.ex

Binary concatenation leads to binary copying
as we traverse the HTML tree. By using IO data,
we traverse the whole tree and build the final
binary once. This dramatically improves performance.

Speed up raw_html by relying on IO data

---

lib/floki.ex
lib/floki/filter_out.ex
test/floki/filter_out_test.exs

feat: `Floki.filter_out/2` now can filter out nodes

---

lib/floki.ex
lib/floki/finder.ex

Fix the spec to indicate that the function accepts `Floki.html_tag()` too.
fixes #269

It uses the correct signature for filter_out/2

---

.github/workflows/ci.yml
README.md
mix.exs

We should only support the 3 latest versions. Since we are too many versions behind, I choose to keep the 4 latest versions and we drop 1.7 soon.

Drop support for Elixir 1.6

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/:checked
The implementation is slightly relaxed due do differences in handling
`checked` vs `checked="checked'` between parsers:
Mochiweb normalizes to `{"checked", "checked"}`:
iex> Application.put_env(:floki, :html_parser, Floki.HTMLParser.Mochiweb)
iex> ~s{<input type="checkbox" id="a" value="1" checked>} |> Floki.parse_document!()
[{"input", [{"type", "checkbox"}, {"checked", "checked"}], []}]
Neither Hhtml5ever nor FastHtml does:
iex> Application.put_env(:floki, :html_parser, Floki.HTMLParser.Html5ever)
iex> ~s{<input type="checkbox" id="a" value="1" checked>} |> Floki.parse_document!()
[{"input", [{"type", "checkbox"}, {"value", "1"}, {"checked", ""}], []}]
We suport both ways.

Support :checked pseudo-class

---

src/floki_mochi_html.erl
test/floki_test.exs

The fix was commented in the code. This also adds a test case with the
difference result expected by each parser.
If closes #305

Fix Mochiweb parse error when there is a XML inside HTML

---

lib/floki.ex
lib/floki/filter_out.ex
lib/floki/finder.ex
lib/floki/html_tree.ex
lib/floki/html_tree/comment.ex
lib/floki/html_tree/html_node.ex
lib/floki/html_tree/text.ex
lib/floki/selector.ex
lib/floki/selector/attribute_selector.ex
lib/floki/selector/combinator.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

This PR deprecates the `Floki.map/2` function in in favour of `Floki.find_and_update/3` or `Enum.map/2`.
This follows the ideas of #286 
With `find_and_update/3` we can refactor functions like `Floki.filter_out/2` to use it.

Deprecate Floki.map/2 and introduce Floki.find_and_update/3

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

This is a very similar PR as the one that adds `:checked` pseudo-selector => https://github.com/philss/floki/pull/301
https://developer.mozilla.org/en-US/docs/Web/CSS/:disabled

Add :disabled pseudo selector

---

.github/workflows/ci.yml
mix.exs

The guard `matrix.elixir >= 1.7` prevented the `inch.report` task to run on all pipelines, since elixir `1.7` isn't list in the matrix I removed the guard and then the task started run.
I upgraded inch_ex because of known bug on version 2.0.0 when the beam file doesn't have the doc chunk and fixed at version 2.1.0-rc.1.

Remove unused guards on CI configuration

---

lib/floki.ex
lib/floki/html_parser.ex

It enables the configuration in runtime rather then by the application
environment. This enables the usage of multiple parsers at once and
is more close to the library guidelides recommendation:
https://hexdocs.pm/elixir/master/library-guidelines.html#avoid-application-configuration
The option has precedence over the application environment configuration.

Add `html_parser` option to `parse_*` functions

---

lib/floki.ex
test/floki_test.exs

This allow the configuration of the logger level and the suppress of
undesirable messages in production.
Closes https://github.com/philss/floki/issues/329

Replace IO.warn by Logger.info for deprecations

---

src/floki_mochi_html.erl
test/floki_test.exs

This is the fix for the issue.
At first I mentioned fixing the issue from the elixir side of things but I quickly realized it would be extremely ugly and probably inefficient.
So I hoped into the erlang code for mochiweb (Seeing erlang syntax for the first time was a bit overwhelming). After digging a bit I came across two function  `tokenize_script` and `tokenize_textarea`.
These functions provide the functionality we want, but for script and textarea tags. I wrote tests to make sure tags that are supposed to be plaintext get parsed correctly. And made them run on both style and script tags.  I was happy to see the tests only failed for the style tag but scripts are working just fine. So I created a function called `tokenize_style` which does what `tokenize_script` does but for style …

Mochiweb - parse style tags as plaintext

---

src/floki_mochi_html.erl
test/floki_test.exs
test/test_helper.exs

Hello again 😀
Title is pretty self explanatory...
In addition to making Mochiweb parse title tags as plaintext, 2 new ExUnit tags were added:
`only_parser` and `except_parser`.
Quoted from the commit description:
> Due to some ExUnit tag limitations we can not use `@tag parser [Parser1, Parser2]`. (ExUnit does not allow tags to be list if they are excluded/included)
That's why the `except_parser` tag was created to run a test for all parsers except a specific one. This works fine when we have only 3 parsers...
> if in the future Floki has more than 3 parsers and a test needs to include only 2, I think the best approach would be to create a test macro that will be used like:
```elixir
test_for_parsers [Parser1, Parser2] do
...
end
```

Mochiweb - parse `title` tag as plaintext, Add `parser` ExUnit tags to skip tests based on current parser

---

.github/workflows/ci.yml
config/config.exs
mix.exs

This change drops support for Elixir 1.8 and 1.9 in order to use recent
versions for `html5ever`.

Require Elixir ~> 1.10

---

README.md
lib/floki/selector.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

Hi,
I needed to add a case insensitive version of fl-contains. I called it fl-icontains. Some websites whose content are hand-written have some case discrepancy on text.
I could not test the whole "mix test" because I keep having troubles compiling html5ever/lexbor on my windows machine.
So I used the default parser and tested manually.
I downcased the strings on the search. I am new to Elixir so there may be some optimization possible.
I will be glad for any suggestions, but please consider this feature as I find it necessary for what I want to do.
Thank you for your great work. I am enjoying this technology.

Added case insentive variation of fl-contains

---

lib/floki.ex

Initially I wondered whether the attribute should be passed as `[data-name]` to match the selector.

Show retrieval of data attributes

---

lib/floki/raw_html.ex
test/floki_test.exs

Fixes [issue 405](https://github.com/philss/floki/issues/405).
Notice: Instead of just appending to the tag list, I have opted to expose the internal default tag list and replace it.
The reason for this is that in some specific xml dialects people would want to write they could replace `<img/>` with `<img>...<img/>` and floki would not be able to support that.
The trade-off here in terms of DX is that if you want to keep the standard html self closing tags you cannot just do:
```elixir
config :floki, :self_closing_tags, ["download"]
```
but you need to do
```elixir
config :floki, :self_closing_tags, ["tags", "you", "want"]
```
I am willing to document this and I hope that this solution passes your checks.
Please let me know if the way I have added unit tests is the the right approach for …

user configurable self closing tags

---

.github/workflows/ci.yml
mix.exs

This makes Floki compatible with the four latest versions of Elixir.

Require Elixir ~> 1.11 and update CI config

---

lib/floki/raw_html.ex
test/floki_test.exs

Oi @philss 
Thanks for your hard work on Floki, it's a great package, we use it in production and it works really well!
I found a small issue when using the `raw_html` function with the `encode: false` option.
On the app I'm working on, we allow users to configure html blocks programatically using the [liquid language](https://shopify.github.io/liquid/). We allow them to use liquid in the content of an HTML tag as well as on the attribute values.
This means that users can end up configuring an element that will look like the following in Floki:
```
{"a",
[
{"href", "{%if 1 > 0 %}\nhttp://www.google.com/\n{%endif%}"},
{"class", "block-button block-button--solid block-button--sm"},
{"style",
"background-color: {{ vars.branding.primary_color | default: default_primary_color }}; …
```

Allow attribute values to not be escaped

---

.github/workflows/ci.yml
mix.exs

Hey there! 
This is a simple quality-of-life check to ensure no unused dependencies are locked by `mix.lock`.

Add unused dependencies check step to CI

---

.github/workflows/ci.yml

This is because the dependency html5ever_elixir is now precompiled. This also updates action versions.

Remove Rust toolchain from CI

---

lib/floki.ex

If you pass a node directly, you'll get an error like
```
The function call will not succeed.
Floki.text(_block :: {<<_::8>>, binary() | [{binary(), binary()}], [any()]})
breaks the contract
(html_tree() | binary()) :: binary()
```

Fix dialyzer issues with Floki.text/1

---

lib/floki/html_parser.ex
lib/floki/html_parser/fast_html.ex
lib/floki/html_parser/html5ever.ex
lib/floki/html_parser/mochiweb.ex
test/floki_test.exs

Hi there!
For testing partials with `fast_html`, we needed to pass arguments to its `parse` method.
Since Floki did not support passing arguments to their HTML Parsers an option to pass arguments to the parser module was added.
Note that this only has effect on `fast_html`, since both `mochiweb` and `html5ever` do not support additional arguments.
**Why we needed this option:**
This was needed because (for example) we had a partial for a table row. When testing this partial on it's own, the output would ignore the `tr` and `td` element, since it was 'invalid html' as the parent `table` element was missing.
This can be solved by passing a `context: "table"` to `fast_html`'s parse function, only Floki did not support passing along arguments.
For example:
``` …
```

Pass arguments to parser modules

---

lib/floki.ex
lib/floki/traversal.ex
test/floki/traversal_test.exs

Hi! This PR adds support for returning a list of nodes in `Floki.traverse_and_update`.
The use case for this is if we want to replace an inline element with a block-level one, i.e.
```html
<p>Code: <code>IO.inspect</code></p>
```
->
```html
<p>Code:</p>
<pre>IO.inspect</pre>
```

Support splitting nodes while traversin

---

src/floki_selector_lexer.xrl
test/floki/selector/parser_test.exs

This pull requests adds an extra rule in the parser in order to prevent escaped class names (`a.xs\\:red-500`) from being parsed as  pseudo selectors.
Closes #411

Parse escaped colons in class names correctly

---

lib/floki.ex
lib/floki/deep_text.ex
lib/floki/flat_text.ex
lib/floki/text_extractor.ex
test/floki/deep_text_test.exs
test/floki/flat_text_test.exs

This pull request adds the `include_inputs?` option to the `Floki.text` function.
Example usage:
```elixir
iex(1)> Floki.text([{"input", [{"type", "date"}, {"value", "2017-06-01"}], []}], include_inputs?: true)
"2017-06-01"
```
Currently it will add into the resulting text all the values from a list of allowed inputs (excluding things such as checkboxes and radios)
Feel free to review and point any changes you would like @philss
Closes #391

Add `include_inputs?` option to Floki.text

---

lib/floki/selector/parser.ex
src/floki_selector_lexer.xrl
test/floki/selector/parser_test.exs
test/floki_test.exs

This is related to the following:
https://github.com/philss/floki/pull/458
https://github.com/philss/floki/issues/411
I decided to push the "cleaning" to the lexer, but I think for more complex escaping rules, we may need to push back to Elixir.

Fix class selector with colon

---

.github/workflows/ci.yml
config/config.exs
mix.exs
test/floki_test.exs
test/test_helper.exs

Instead, create a new task named "test_all" to run all backends. Now the tests of each parser can be executed with `mix test_parser`, where "parser" can be "mochiweb", "fast_html" or "html5ever".

Remove override of `mix test` task

---

lib/floki.ex
lib/floki/html_parser.ex
lib/floki/html_parser/fast_html.ex
lib/floki/html_parser/html5ever.ex
lib/floki/html_parser/mochiweb.ex
lib/floki/selector.ex
lib/floki/selector/attribute_selector.ex
lib/floki/selector/pseudo_class.ex
src/floki_mochi_html.erl
test/floki_test.exs

This is a feature request from https://github.com/philss/floki/issues/463 and is the base for implementing the same feature in more backends.
Right now only the built-in `mochiweb` parser implements the feature.

Add support for parsing attributes as maps

---

README.md
lib/floki/finder.ex
lib/floki/selector.ex
lib/floki/selector/parser.ex
lib/floki/selector/pseudo_class.ex

Closes https://github.com/philss/floki/issues/481

Change log level from "info" to "debug"

---

mix.exs

Before this patch on Elixir main:
~/src/floki[main]% mix compile --force
warning: in order to compile .xrl files, you must add "compilers: [:leex] ++ Mix.compilers()" to the "def project" section of your mix.exs
(mix 1.17.0-dev) lib/mix/tasks/compile.leex.ex:69: Mix.Tasks.Compile.Leex.preload/1
(mix 1.17.0-dev) lib/mix/compilers/erlang.ex:66: Mix.Compilers.Erlang.compile/6
(mix 1.17.0-dev) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
(mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:124: Mix.Tasks.Compile.All.run_compiler/2
(mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:104: Mix.Tasks.Compile.All.compile/4
(mix 1.17.0-dev) lib/mix/tasks/compile.all.ex:93: Mix.Tasks.Compile.All.with_logger_app/2
Compiling 1 file (.xrl)
Compiling 2 files (.erl)
Compiling 31 files (.ex)
Generated …

Add :leex to Mix compilers

---

lib/floki/raw_html.ex
test/floki_test.exs

When parsing using the new option :attributes_as_maps, I got errors when trying to convert back with the raw_html function.  This changes the Map into a list where the error occurs and continues regular processing.

Update raw_html.ex to handle :attributes_as_maps option

---

lib/floki.ex
test/floki_test.exs

Today I had an issue where I accidentally passed `{:ok, tree}` into the `find/2`. I think it might not be a bad idea to protect the input with a guard. People who can't read the docs like me might save some frustration.
This is purely proposal. If I get a green light for this I will make develop this PR properly.

`find/2` input protection proposal.

---

lib/floki/html_parser/fast_html.ex
lib/floki/html_parser/html5ever.ex
lib/floki/html_parser/mochiweb.ex
test/floki_test.exs

`parse_document` and `parse_fragment` declare in their spec that they support `iodata()`, but this format is not actually working today. 
This PR adds support to IO data on all parsers, which is useful specially on mochiweb, since it has to add a `<floki>` tag around the html.

Enable parse of IO data html

---

lib/floki/raw_html.ex

While doing benchmarks on a Phoenix LiveView project, I saw that `build_attrs/2` spent a lot of time running `Function.info/1` to check if we wanted to skip the HTML.
This PR replaces `Function.info` a simple equals check to see if the value is the same `@encoder`.
`:fprof` results before
```
%                                                     CNT                           ACC                           OWN
[{ totals,                                           4183972,                     6249.692,                     6096.914}].  %%%
...
{[{{'Elixir.Floki.RawHTML','-tag_attrs/2-fun-0-',2},   10952,                     1101.148,                       43.927}],
{ {'Elixir.Floki.RawHTML',build_attrs,2},             10952,                     1101.148,                       43.927},     % …
```

Optimize RawHTML.build_attrs/2

---

src/floki_mochi_html.erl

`tokenize_literal` already changes this value to lower case, so in `parse_flag`  we can do a binary pattern match directly instead of running lower case in this value again.

Optimize parse_flag

---

lib/floki/finder.ex

Today `find_selectors`  and it's child functions use `Enum.flat_map` to interact through the nodes to find the matching ones.
This PR replaces the `Enum.flat_map` and `Enum.map`  usages with recursion, removing most of the intermediate lists this methods had, and also simplifying `traverse_with` implementation.
This also provides a really small performance improvement. When checking this benchmark with fprof, operations count went from 65867 to 57726, reducing the time to run with fprof from 115ms to 95ms.
```
Name            ips        average  deviation         median         99th %
pr           555.12        1.80 ms    ±13.53%        1.72 ms        2.75 ms
today        544.31        1.84 ms    ±12.83%        1.75 ms        2.79 ms
Comparison: 
pr           555.12
today        544.31 - …
```

Use recursion instead of Enum.flat_map on find_selectors

---

lib/floki/html_tree.ex

Today when HTMLTree.build is called, after each element is build, the parent node children_nodes_ids list is updated, and the parent node and current node are put on tree.nodes map. This repeated updates ends up being quite costly on both memory and CPU.
This PR applies multiple changes to this module to significantly reduce the tree building cost:
- Add parent_node to tree.nodes only after all it's children are build and added to children_nodes_ids - benchmark reduced-updates
- During build, instead of storing the nodes as map and updating it on each built node, store the node as list of {node_id, node}, and build the map only at the end - benchmark reduced-updates
- Instead of using HTMLTree on build_tree calls, use node_ids and nodes values directly - benchmark pr
```
Name …
```

Optimize HTMLTree.build

---

lib/floki/entities.ex
lib/floki/raw_html.ex
test/floki/entities_test.exs

Floki today has two similar encoding functions, Floki.Entities.encode and Floki.RawHTML.html_escape.
This PR moves the html_escape code to the Entities module, ensuring we always use the fastest encoding function available.
```
Name                    ips        average  deviation         median         99th %
bench                 50.48       19.81 ms     ±8.35%       19.23 ms       26.89 ms
bench (today)         25.47       39.26 ms    ±10.21%       38.05 ms       55.82 ms
Comparison: 
bench                 50.48
bench (today)         25.47 - 1.98x slower +19.45 ms
Memory usage statistics:
Name             Memory usage
bench                 9.49 MB
bench (today)         9.23 MB - 0.97x memory usage -0.25281 MB
**All measurements for memory usage were the same**
Name …
```

Always use optimal encoding function

---

lib/floki/selector.ex
lib/floki/selector/attribute_selector.ex
lib/floki/selector/parser.ex
test/floki/selector/parser_test.exs

Apply some optimizations on selector matching to try to avoid expensive calls:
- Use list instead of regex for String.split - [benchmark](https://github.com/philss/floki/pull/509)
- Don't try to match class if attribute value bit_size is smaller than the first class in the selector
- Reorder selector classes to put longest classes first, to optimize the check above
- Use equals when there's a single class selector and the class attribute value has the same bit_size as the selector
- Compute minimal class attribute value bit_size, and avoid split if this condition isn't match 
- on `match?`, check if selector requires descendant, and skip other checks if the current node doesn't have descendants
```
Name                 ips        average  deviation         median         99th %
bench (pr) …
```

Optimize selectors matching

---

lib/floki/finder.ex

Today Finder uses Enum.reduce and nested calls to traverse_with to do it's filtering.
This works fine when using HTMLTree, but this structure makes it harder to optimize some cases in which the HTMLTree isn't necessary (https://github.com/philss/floki/issues/515).
This PRs updates Finder to use a stack, similar to what we have on HTMLTree.build_tree. This makes it easier to implement the change for the ticket above, or other future changes to operations that don't need the HTMLTree.build step.
I also did some other clean ups in this module, I've split each change in a separated commit.
Performance is basically the same, but when profiling the timing is a lot better and more readable because of the removal of Enum.reduce
Before - selector `span a * i` 
```
% …
```

Use stack on Finder

---

lib/floki/raw_html.ex

`self_closing_tags` is not a slow function, but today it is called thousands of times while generating the raw html, which ends up causing a significant performance impact. 
This PR modifies the RawHTML module to call `self_closing_tags()` only once on `raw_html`, sending the value as params to the other functions. `raw_html` also converts closing tags to MapSet to help speed up the check .
```
Name                 ips        average  deviation         median         99th %
bench (pr)         61.60       16.23 ms    ±14.47%       15.99 ms       21.96 ms
bench              39.96       25.03 ms     ±9.18%       24.86 ms       31.23 ms
Comparison: 
bench (pr)         61.60
bench              39.96 - 1.54x slower +8.79 ms
Memory usage statistics:
Name          Memory usage
bench (pr) …
```

Call self_closing_tags only once on raw_html

---

lib/floki/selector.ex

Today the id matching goes through all node attributes trying to find an exact id, even after checking an id attribute with a different value.
This PR changes the check find the first attribute `id` instead of keep checking the remaining attributes. 
When using attributes as lists performance is basically the same, but for attributes as maps performance improved significantly. 
For both cases the memory usage is reduced.
```
Name                               ips        average  deviation         median         99th %
attributes_as_maps (pr)         158.48        6.31 ms    ±23.60%        6.19 ms        9.87 ms
attributes_as_lists (pr)        158.37        6.31 ms    ±25.44%        6.15 ms       10.31 ms
attributes_as_lists             157.35        6.36 ms    ±22.13%        6.25 ms …
```

Optimize id matching

---

lib/floki/raw_html.ex

Today leftpad calls String.duplicate, which ends up being significantly costly when generating a pretty raw html, since this is used on each line being generated.
This PR moves the string creation to `pad_increase`, instead of doing it on every call to `leftpad`.
```
Name                 ips        average  deviation         median         99th %
bench (pr)         35.87       27.88 ms    ±11.34%       27.06 ms       41.01 ms
bench              33.05       30.26 ms     ±6.39%       30.00 ms       34.48 ms
Comparison: 
bench (pr)         35.87
bench              33.05 - 1.09x slower +2.38 ms
Memory usage statistics:
Name          Memory usage
bench (pr)        12.68 MB
bench             13.83 MB - 1.09x memory usage +1.15 MB
**All measurements for memory usage were the same**
Name …
```

Optimize leftpad on raw_html

---

lib/floki/raw_html.ex
test/floki_test.exs

After https://github.com/philss/floki/pull/512, Entities.encode returns iodata instead of string when the content if the content got encoded. 
RawHTML.leftpad_content was expecting a string, which caused it to fail when trying to trim the value.

Fix pretty raw_html with encoded text

---

lib/floki/selector.ex

Today in the Selector module, each match function has it's code to extract the node type or attributes from HTMLNode to run it's matching condition.
To make it easier to implement #515, this PR moves this data extraction to common functions, which will avoid having to deal on each type of match with HTMLNode or html tuples + attributes as maps or attributes as lists.

Move data extraction for selector matching

---

lib/floki.ex
lib/floki/finder.ex

Today Finder.find expects a list of html_node tuples, and returns an HTMLTree and a list of resulting HTMLNode.
To allow the changes for #515, we need to return html_nodes only when we don't need to later use the HTMLTree. If receiving an HTMLTree, Finder.find will return a  list of HTMLNode, and if receiving a list of html_nodes the return will be a list of html_nodes. 
For now we'll keep building an HTMLTree for the search, but this allow a future change to avoid building the HTMLTree on simple selectors without having to change modules using Finder.
This is a breaking change for projects using Finder.find directly.

Polymorphism on Finder.find

---

lib/floki.ex
lib/floki/finder.ex
test/floki_test.exs

To make sure we don't have any regression on the changes for https://github.com/philss/floki/issues/515, we need to run all selector tests with both html node tuple list and with HTMLTree.
This PR modifies most asserts on Floki.find to use `assert_find`, which will check the results of Floki.find with an html node tuple list, and then check if the result is the same when calling Floki.Finder.find with an HTMLTree. 
On tests that have to use pattern matching instead of equals, the comparison is done directly in the test instead of using `assert_find`.
Depends on #522

Run all selector test with tuple list and html tree

---

lib/floki/finder.ex

Today `traverse_with`  is implemented in a way to make the pattern matching easier and split into multiple calls. This is causing `traverse_with` to be called three times for each element, one to get the top of the stack, one to get the first element of the list, and another to do the actual processing of the element. 
This PR updates traverse_with to use the stack directly, providing a small performance improvement and memory reduction
Finder benchmark
```
Name                             ips        average  deviation         median         99th %
id (pr)                       1.71 K        0.58 ms    ±17.13%        0.60 ms        0.84 ms
id (main)                     1.50 K        0.66 ms    ±21.56%        0.63 ms        1.32 ms
class (pr)                    1.29 K        0.77 ms …
```

Reduce number of function call on traverse

---

lib/floki.ex
test/floki_test.exs

Floki.children is called a lot by Phoenix LiveView when doing tests. On the project I'm working on, this functions gets called more than 8 million times when running all of our tests. 
This PR adds some pattern matching to this function to avoid using `Access.get` if possible.
```
Name                      ips        average  deviation         median         99th %
children (pr)         11.50 K       86.95 μs   ±239.29%       53.26 μs     1559.21 μs
children (main)        7.19 K      139.07 μs   ±145.06%      104.25 μs     1507.63 μs
Comparison: 
children (pr)         11.50 K
children (main)        7.19 K - 1.60x slower +52.12 μs
``` 
```
read_file = fn name ->
__ENV__.file
|> Path.dirname()
|> Path.join(name)
|> File.read!()
|> Floki.parse_document!()
end
doc = read_file.("small.html") …
```

Optimize Floki.children

---

lib/floki/finder.ex
lib/floki/selector.ex

We finally got to this PR, after all of the preparation PRs.
With this PR changes, we'll check if we can run the search directly in the raw html nodes instead of building an html tree. To keep it simple for now, this will be applied only if find is called with a single selector that is not a composite selector nor uses pseudo-classes.
Composite selectors will require some more work, but it looks possible to do. Some pseudo-classes don't require the tree and should be easy to enable, like `:disabled`, but the other pseudo-classes will be a lot more complicated, and will require some investigation to see how hard it would be to implement them. 
Benchmark results are a lot better than I expected, specially on big documents.
```
Name                             ips        average  deviation …
```

Find without build html tree

---

lib/floki/selector.ex

Today the namespace and type matching use String.split to get the namespace and type of an element. 
Using pattern matching instead of String.split provides a significant performance improvement, bringing the type selector performance closer to the id selector. 
```
Name                             ips        average  deviation         median         99th %
id                            477.46        2.09 ms    ±20.92%        1.91 ms        3.45 ms
tag name (type) (pr)          384.54        2.60 ms    ±24.84%        2.31 ms        4.64 ms
tag name (type) (main)        158.85        6.30 ms    ±13.58%        6.04 ms        9.55 ms
Comparison: 
id                            477.46
tag name (type) (pr)          384.54 - 1.24x slower +0.51 ms
tag name (type) (main)        158.85 - 3.01x …
```

Optimize type selector by using pattern match

---

lib/floki/raw_html.ex

- Use Enum.map_intersperse instead of custom map_intersperse implementation
- Unify no encoder declaration instead of having multiple places declaring `& &1`

Raw HTML code clean up

---

lib/floki/finder.ex
test/floki_test.exs

Instead of expecting `traverse_html_tree` to return elements in the correct order, we'll now use the `node_id` to sort find results.
Fixes #539

Always return find elements in the correct order

---

lib/floki/finder.ex

This PR applies the new optimized find when the selector contains only descendant selector. The performance improvement on this one is even higher than in the previous PR, and is pretty close to a find using a selector without descendant. 
For descendant selector the html tree traversal ends up traversing the same element multiple times. In this traverse we'll check each element only once.
This happens because this traverse doesn't add all element upfront with the initial selector, and instead add each children as we navigate the stack. On a match, we can add the children items with the combinator selector directly, which avoids traversing this element twice and avoids duplicating the element in the result, which we are not able to dedup on this find. 
```
Name …
```

Find using descendant selector without html tree

---

lib/floki/finder.ex
lib/floki/selector/parser.ex
test/floki_test.exs

`+` combinator was being parsed as `:sibling`, while `Floki.Selector.Combinator` expected `:adjacent_sibling` to be used for this combinator. 
This PR changes all all usages of  `:sibling` to `:adjacent_sibling`

Use adjacent_sibling instead of sibling

---

lib/floki.ex
lib/floki/html_parser.ex
lib/floki/raw_html.ex
test/floki_test.exs

This PR is blocked by [this one](https://github.com/philss/floki/pull/541).

Improve opts validation with Keyword.validate!/2

---

lib/floki.ex
test/floki_test.exs

Related to the problem and discussion in https://github.com/phoenixframework/phoenix_live_view/issues/3144.
In LiveViewTest we need to find elements by their id. Currently, we use `Floki.find(html, "##{id}")`, but this breaks as soon as there are special characters in the id. We could use `Floki.find(html, %Floki.Selector{id: id})`, but the `Floki.Selector` struct is not documented and therefore I'm not sure if it's something to rely on.
As `document.getElementById` is also a frequently used API in the browser, adding a `find_by_id` or similar function to Floki could be quite useful.
This PR adds a simple find_by_id function that internally uses the `%Floki.Selector{id: id}` struct.
As using find with a string is deprecated, I did not add this functionality to find_by_id.

add Floki.find_by_id/2

---

lib/floki/finder.ex

This PR adds support for the remaining combinator match types in traverse_html_tuples.
To avoid making this a lot more complex on child and adjacent sibling, this optimized traversal will happen only if these combinators are the last combinator in the selector. Without this limitation we'd need to keep track of a lot of information to not duplicate nodes in the response. 
This also adds a small documentation to `traverse_html_tuples` explaining how we are keeping track of the multiple combinators types. 
```
Name                                         ips        average  deviation         median         99th %
tag name (type) (main)                    545.35        1.83 ms    ±21.21%        1.73 ms        3.37 ms
tag name (type) (pr)                      531.10        1.88 ms    ±13.70% …
```

Find without html tree for the remaining combinators

---

lib/floki.ex

well... so I forgot to change the typespec when changing the function to return a node or nil instead of a tree.
This fixes that.

fix typespec of get_by_id/2

---

lib/floki/raw_html.ex
test/floki_test.exs

`parse_document` correctly treats the content of title tags as plain text. But `raw_html` does not. This PR fixes that.

raw_html treats the content of title tags as plain text

---

lib/floki/raw_html.ex

As discussed in #552, with the recent changes to how the opts are read in the RawHTML module, the `encode_raw_html` configuration option is never read.
With this change, the `encode_raw_html` value set in the environment is used as the default or true if it does not exist, which is in line with how it behaved up until now.

fix: read encode_raw_html config as default for raw_html encode option

---

CHANGELOG.md
mix.exs

This release would let us upgrade LiveView without breaking some of our tests, now that the fix #561 has been merged!

Release 0.36.2

---

lib/floki/finder.ex
lib/floki/selector/pseudo_class.ex

This PR adds support for traversal without building HTMLTree for the pseudo-classes that don't require tree information - `:checked`, `:disabled`, and `:not` not using any of the other pseudo-classes. 
Final PR for https://github.com/philss/floki/issues/515
```
Name                                       ips        average  deviation         median         99th %
checked (pr)                            593.06        1.69 ms     ±8.05%        1.66 ms        2.22 ms
disabled (pr)                           593.05        1.69 ms     ±7.67%        1.66 ms        2.19 ms
not checked (pr)                        588.96        1.70 ms    ±13.37%        1.66 ms        2.58 ms
checked (v0.36.2-4-gc3417a5)             35.65       28.05 ms    ±58.88%       21.24 ms       83.09 ms
disabled …
```

Find without html tree for some pseudo classes

---

lib/floki/finder.ex

On https://github.com/philss/floki/pull/518 I added the stack concept on the on Finder to make it easier to implement the search without HTMLTree. Since we ended up with separated functions to do the traversal with or without the tree, the stack ends up being an unnecessary performance overhead, and makes the code harder to read.
This PR replaces all stack usages and uses recursion to do the traverse the nodes. 
```
Name                                           ips        average  deviation         median         99th %
id (PR)                                     736.59        1.36 ms     ±8.70%        1.31 ms        1.87 ms
tag name (type) (PR)                        623.02        1.61 ms     ±9.32%        1.57 ms        2.19 ms
id (v0.36.2-4-gc3417a5)                     546.58 …
```

Remove stack usage on Finder

---

lib/floki/raw_html.ex
test/floki_test.exs

Today nodes without attributes have an unnecessary space between the element type and `>` when transforming to raw HTML

Remove extra whitespace on node without attributes

---

lib/floki.ex
lib/floki/finder.ex
lib/floki/selector.ex

Today get_by_id just calls Finder.find and gets the first item in the list.
This PR refactors this method to avoid the unnecessary checks on `match?` and check the id value directly, and to stop the traversal on the first matching element.
```
Benchee.run(
%{
"get_by_id - beginning document" => fn doc -> Floki.get_by_id(doc, "mw-page-base") end,
"get_by_id - end document" => fn doc -> Floki.get_by_id(doc, "footer-poweredbyico") end
},
time: 10,
inputs: inputs,
save: [path: "benchs/results/finder-#{tag}.benchee", tag: tag],
memory_time: 2
)
```
```
Name                                                          ips        average  deviation         median         99th %
get_by_id - beginning document (PR)                      691.49 K     0.00145 ms  ±2360.83%     0.00124 ms     0.00233 ms …
```

Stop get_by_id traversal on first match

---

lib/floki/traversal.ex

Today `traverse_and_update/2` calls the same traverse functions as `traverse_and_update/3`, so the traverse keeps creating a bunch of tuples to store the accumulator value unnecessarily. 
This PR optimizes `traverse_and_update/2`  by avoiding this tuples, it required basically duplicating the traverse functions, since the implementation is small it shouldn't be an issue.
```elixir
read_file = fn name ->
__ENV__.file
|> Path.dirname()
|> Path.join(name)
|> File.read!()
|> Floki.parse_document!()
end
inputs = %{
"big" => read_file.("big.html"),
"medium" => read_file.("medium.html"),
"small" => read_file.("small.html")
}
Benchee.run(
%{
"delete footer-poweredbyico" => fn doc ->
Floki.traverse_and_update(doc, fn node ->
if Floki.attribute(node, "id") == ["footer-poweredbyico"] do
nil
else …
```

Optimize traverse_and_update without accumulator

---

lib/floki/raw_html.ex

Today raw_html creates a new list wrapping up the sibling current `html` value before adding the current node data, causing a small memory overhead. 
This PR moves raw_html to use an accumulator, simplified `build_raw_html` a bit by always expecting a list and merged `tag_for` into the only `build_raw_html` that was using it.
```
Name                   ips        average  deviation         median         99th %
bench (pr)           48.88       20.46 ms     ±6.66%       20.37 ms       25.04 ms
bench (main)         43.07       23.22 ms    ±15.12%       22.69 ms       30.49 ms
Comparison:
bench (pr)           48.88
bench (main)         43.07 - 1.13x slower +2.76 ms
Memory usage statistics:
Name            Memory usage
bench (pr)          12.12 MB
bench (main)        12.50 MB - 1.03x memory …
```

Use accumulator on raw_html

---

lib/floki.ex

The function uses `List.wrap` internally, which means it accepts any `html_node`
Inadvertently, I created this bug 6 years ago!

Fix raw_html/2 typespec

---

lib/floki.ex
lib/floki/css_escape.ex
test/floki/css_escape_test.exs

Closes https://github.com/philss/floki/issues/554.

add Floki.css_escape/1

---

lib/floki/raw_html.ex
test/floki_test.exs

Hi! We noticed a bug when going to upgrade Floki. It seems that any tag that is set to the `identity` encoder would propagate that encoder through the rest of the tree (instead of just to its' children). I've added a test case here taken from some real Appcues content that triggers this behavior. Without this fix, it's _very_ possible for Floki to emit broken HTML. If you parse any `script` or `style`, tag, the identity encoder would be applied, which would in this case, emit an un-escaped `data-attrs-event` tag (even if escaping is explicitly enabled!). I'm dubious on if it's the duty to handle not decoding the entities in the parser, but I'm 100% sure this is a bug as-is.

Fix bug propagating identity encoder in `raw_html/2`

---

lib/floki/selector/parser.ex
src/floki_selector_lexer.xrl
test/floki/selector/parser_test.exs

Notice that we don't accept combinators yet. This is like the `:not()` selector.
This is related to the issue https://github.com/philss/floki/issues/482

Implement parsing rules for the `:has` pseudo class selector

---

README.md
lib/floki/selector.ex
lib/floki/selector/parser.ex
lib/floki/selector/pseudo_class.ex
test/floki_test.exs

Fixes #482, #382, #592  
TODO:

feat: implement :has pseudo-selector functionality

---

lib/floki.ex

This adds documentation for the `:style` keyword argument, which was previously demonstrated in the code examples, but not listed explicitly in the options section.

Add `:style` flag to text/2` docs

---

lib/floki/finder.ex
test/floki/selector/parser_test.exs
test/floki_test.exs

Closes https://github.com/philss/floki/pull/605

Prevent `find/2` from crashing with empty selector
