- lib/floki.ex
- lib/floki/deep_text.ex
- lib/floki/flat_text.ex
- test/floki/deep_text_test.exs
- test/floki/flat_text_test.exs
> add optional separator to text function

- lib/floki.ex
- lib/floki/finder.ex
- test/floki_test.exs
fixes https://github.com/philss/floki/issues/65
Just uses Elixir's pattern matching on the html tree structure. This is how I'd implement the function outside of the library. Maybe there's a more efficient way using Floki's selector engine?
> first attempt at transform function

- mix.exs
- mix.lock
You can see the reasoning inside #68 
Thanks!
EDIT: I have also confirmed that this works and that the release builds and works...
> changed to full mochiweb package to stop duplicates inside a release

- lib/floki/finder.ex
- lib/floki/selector_parser.ex
- lib/floki/selector_tokenizer.ex
- src/floki_selector_lexer.xrl
- test/floki/selector_parser_test.exs
- test/floki_test.exs
Works good with simple selectors as the specs suggest.
- https://developer.mozilla.org/en-US/docs/Web/CSS/:not
Issue: https://github.com/philss/floki/issues/82
> Add "not" pseudo-class selector

- lib/floki/finder.ex
- test/floki_test.exs
It fixes issue #96.
And also fixes problems with other combinators.
> Fix search for selectors with combinators and pseudo-classes

- CHANGELOG.md
- lib/floki.ex
- lib/floki/selector_parser.ex
- mix.exs
- mix.lock
- test/floki/selector_parser_test.exs
- test/floki_test.exs
I had to change the href's of some links and it seemed easier to be done with Floki's HTMLTree structure so I added a function to do it. I think functions similar to jQuery.text and jQuery.html would be cool too and I may be able to implement that, I'm pretty sure the implementation isn't as clean as it should be, so, thanks for your attention.
> added Floki.attr/4

- lib/floki.ex
If it is absent the mutation function is being called with `nil`. This
allows to add an attribute.
> Fix attr function when the attribute is absent

- .travis.yml
- lib/floki.ex
- lib/floki/filter_out.ex
- lib/floki/selector/tokenizer.ex
- test/floki_test.exs
Also improve code for readability.
> Remove warnings from Elixir 1.5

- CODE_OF_CONDUCT.md
We should provide a more friendly, safe and welcoming environment for all.
> Add a code of conduct based on Elixir's CoC

- lib/floki/selector/functional.ex
- lib/floki/selector/parser.ex
- lib/floki/selector/pseudo_class.ex
- test/floki/selector/functional_test.exs
- test/floki/selector/parser_test.exs
- test/floki_test.exs
https://developer.mozilla.org/en-US/docs/Web/CSS/:nth-child#Functional_notation
Closes #145
> Add Functional Notation nth-child selector

- lib/floki.ex
- lib/floki/deep_text.ex
- lib/floki/filter_out.ex
- lib/floki/finder.ex
- lib/floki/flat_text.ex
- lib/floki/html_parser/html5ever.ex
- lib/floki/html_tree.ex
- lib/floki/selector.ex
- lib/floki/selector/attribute_selector.ex
- lib/floki/selector/combinator.ex
- lib/floki/selector/functional.ex
- lib/floki/selector/parser.ex
- lib/floki/selector/pseudo_class.ex
- lib/floki/selector/tokenizer.ex
- test/floki/deep_text_test.exs
- test/floki/flat_text_test.exs
- test/floki/html_tree_test.exs
- test/floki/selector/parser_test.exs
- test/floki/selector/tokenizer_test.exs
- test/floki/selector_test.exs
- test/floki_test.exs
sorry @philss, didn't splitted format commits by file.
#142
> Format all files

- mix.exs
This should enable the app to run correctly in production.
It fixes https://github.com/philss/floki/issues/163
> Include HTML entities to the applications list

- lib/floki.ex
- test/floki_test.exs
> Fix serialization of the tree after updating attribute.

- .credo.exs
- lib/floki/filter_out.ex
- lib/floki/html_tree.ex
- lib/floki/raw_html.ex
- lib/floki/selector.ex
- lib/floki/selector/functional.ex
- lib/floki/selector/parser.ex
- test/floki/deep_text_test.exs
- test/floki/html_tree_test.exs
- test/floki_test.exs
There are still some consistency issues, but we can fix those with the formatter (which I will do in another PR if thats cool).
> fix some credo issues

- CHANGELOG.md
- lib/floki.ex
- lib/floki/filter_out.ex
- lib/floki/finder.ex
- lib/floki/html_tree.ex
- lib/floki/selector/pseudo_class.ex
- mix.exs
- mix.lock
- test/floki/html_tree_test.exs
This PR fixes the bug reported in #175. It also changes the way we build the root nodes ids to be a little bit more efficiency.
> Fix build tree with comment

- CHANGELOG.md
Because https://github.com/philss/floki/issues/161#issuecomment-382692593
> Add info about a breaking change in 0.19.2

- .travis.yml
- mix.exs
closes https://github.com/philss/floki/issues/190
> Remove ex 1.3 add ex 1.7

- .travis.yml
Fix for Issue #191 
Add script step to execute formatter (if version is > 1.5) and execute the tests in build pipeline
> Run the formatter on build

- lib/floki.ex
- lib/floki/traversal.ex
- test/floki/traversal_test.exs
Let me know if there's anything you want me to change/add.
> Add Floki.traverse_and_update/2. Fix #206.

- lib/floki/raw_html.ex
- test/floki_test.exs
Fixed: #209 
With reference from https://github.com/mischov/meeseeks/pull/64
> Escape problematic characters when encoding to html

- lib/floki/selector/attribute_selector.ex
- test/floki_test.exs
> Add support for tabs in attribute selectors

- .github/workflows/ci.yml
> Add github actions workflow

- lib/floki.ex
Since `traverse_and_update/2` and `traverse_and_update/3` can encounter
and process not just HTML tags, but also - for example HTML comments -
the function passed as argument has to be aware of these possibilities.
Otherwise the function will crash.
This code change updates documentation to make user aware that this can
and will happen when parsing HTML, and also updates examples/doctests to
always have the second function clause to handle arguments which are not
HTML tags.
> Update traverse_and_update/2 and /3 docs and tests

- .github/workflows/ci.yml
- mix.exs
Closes #312
Updated the mix.exs file
> Require Elixir version ~> 1.8

- lib/floki.ex
- lib/floki/raw_html.ex
- lib/floki/selector.ex
- lib/floki/selector/functional.ex
- lib/floki/selector/parser.ex
- test/floki_test.exs
This is an attempt to solve https://github.com/philss/floki/issues/249
I think there is still room to improve, like making the padding character and line ending customizable, but I'd like to know if this is what you guys expect from this issue and if the way I tried to solve it is acceptable.
> Adds pretty option to raw_html

- README.md
Document workaround for https://github.com/philss/floki/issues/352
> Document selector for ids with periods

- lib/floki/selector/pseudo_class.ex
- test/floki_test.exs
> Allow root nodes to be selected using pseudo-classes

- src/floki_mochi_html.erl
Like this? I didn't check the html5ever and fast_html parsers. 
https://github.com/philss/floki/issues/399
> remove case of 2 tuple of :pi

- lib/floki.ex
> Fix traverse_and_update/3 spec

- lib/floki/selector/parser.ex
- test/floki/selector/parser_test.exs
This is a fix for when a "pseudo-class" ":not" that contains an attribute selector is followed by another selector. This is an example: "a:not([class]), div".
The solution was to avoid using the general parsing state for the attribute, and instead use the "consume attribute" state, which is more predictable.
Closes https://github.com/philss/floki/issues/441
> Fix pseudo-class ":not" selector parsing halting point

- src/floki_mochi_html.erl
This is an attempt to cleanup that file in order
to make easier to introduce new features.
This file was also formatted using Whatsapp's [erlfmt](https://github.com/WhatsApp/erlfmt).
> Remove unused functions from `floki_mochi_html`

- .gitignore
As generated by `mix test --cover`
> Ignore .cover folder

- lib/floki.ex
Some of them are there for almost 4 years.
> Remove deprecations
